import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// The launcher icon is generated by `tool/generate_icon.py` and then lives in
/// three places: the macOS asset catalogue, `assets/icons/macos/` and
/// `assets/icons/linux/`. Nothing connects them at build time — each
/// packaging step copies whatever files it finds.
///
/// So when the icon was redesigned and the generator wrote only the macOS
/// targets, Linux kept the previous design through six releases. It was not
/// subtle when measured — a darkest point of 0 where the redesign had removed
/// pure black, and 0.12% of pixels bright against 4.67% — but nothing was
/// measuring, and the icon is the one part of an application nobody reads a
/// diff of.
void main() {
  const sharedSizes = [16, 32, 64, 128, 256, 512];

  /// The sizes each packaging installs. Kept in step with the `for size in`
  /// loops in scripts/build_deb.sh and snap/snapcraft.yaml.
  const linuxSizes = [16, 24, 32, 48, 64, 128, 256, 512];
  const macosSizes = [16, 32, 64, 128, 256, 512, 1024];

  File linux(int size) => File('assets/icons/linux/mixterm_$size.png');
  File macos(int size) => File('assets/icons/macos/app_icon_$size.png');
  File catalogue(int size) => File(
      'macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_$size.png');

  group('every platform ships the same icon', () {
    test('the sizes each packaging asks for all exist', () {
      for (final size in linuxSizes) {
        expect(linux(size).existsSync(), isTrue,
            reason: 'the .deb and the snap both install ${size}px');
      }
      for (final size in macosSizes) {
        expect(catalogue(size).existsSync(), isTrue,
            reason: 'the asset catalogue references ${size}px');
      }
    });

    test('shared sizes are byte-identical across platforms', () {
      // The check that would have caught the drift. Same generator, same
      // source, same size — so the bytes have to match. If they do not,
      // somebody regenerated one platform and not the others.
      for (final size in sharedSizes) {
        expect(linux(size).readAsBytesSync(), macos(size).readAsBytesSync(),
            reason: 'linux/mixterm_$size.png and macos/app_icon_$size.png '
                'differ — run tool/generate_icon.py, which writes both');
      }
    });

    test('the macOS catalogue matches the assets it was generated with', () {
      for (final size in sharedSizes) {
        expect(catalogue(size).readAsBytesSync(), macos(size).readAsBytesSync(),
            reason: 'the asset catalogue has drifted from assets/icons/macos');
      }
    });
  });

  group('the generator writes every packaged location', () {
    final generator = File('tool/generate_icon.py').readAsStringSync();

    test('it names the Linux target', () {
      // Written as a test rather than trusted, because the omission is
      // invisible: the script succeeds, and the stale files stay put.
      expect(generator, contains('assets/icons/linux/mixterm_%d.png'),
          reason: 'a generator that skips a platform leaves it on the old '
              'design with no error anywhere');
    });

    test('it names the macOS targets', () {
      expect(generator, contains('assets/icons/macos/app_icon_%d.png'));
      expect(generator, contains('AppIcon.appiconset/app_icon_%d.png'));
    });

    test('it covers the sizes the Linux packaging installs', () {
      // build_deb.sh and snapcraft.yaml both loop over these; a size the
      // generator does not write is a size that stays stale.
      final listed = RegExp(
              r'assets/icons/linux/mixterm_%d\.png":\s*\[([\s\d,]+)\]')
          .firstMatch(generator);
      expect(listed, isNotNull, reason: 'no size list for the Linux target');

      final sizes = RegExp(r'\d+')
          .allMatches(listed!.group(1)!)
          .map((m) => int.parse(m.group(0)!))
          .toSet();

      expect(sizes, containsAll(linuxSizes));
    });
  });
}
